### ISSUE TITLE
Login popup form design

### ISSUE THREAD

**Issue by andrekosak** [jonmbake/discourse-ldap-auth#11]
The LDAP Login form looks quite old-styled.
Would it make sense to use the same styling as Discourse has?

![bildschirmfoto 2016-08-25 um 13 24 39](https://cloud.githubusercontent.com/assets/6382243/17967417/59756656-6ac7-11e6-92d2-ff8953a85316.png)

**Comment by jonmbake** [comment]
The plugin wraps https://github.com/intridea/omniauth-ldap. It is currently using the default `OmniAuth` styling: https://github.com/omniauth/omniauth/blob/master/lib/omniauth/form.css. I think we might be able to hook into OmniAuth styling in `OmniAuth.config.form_css`: https://github.com/omniauth/omniauth/blob/1cc1cf4b2821a7d2a4a376a5ca93c61b6bd8b5f1/lib/omniauth.rb... not sure, have to look into it more.

**Comment by tedstrauss** [comment]
Subscribing.
Would love to see the LDAP login better integrated with Discourse's.

**Comment by jonmbake** [comment]
Tweaked the styling a bit.. still not perfect:

[New Form](https://github.com/jonmbake/screenshots/blob/master/discourse-ldap-auth/ldap_popup.png)

Anyone feel free to update further: https://github.com/jonmbake/discourse-ldap-auth/blob/master/css/fom.css
