### ISSUE TITLE
"Login with LDAP" button misunderstood as headline

### ISSUE THREAD

**Issue by xldrkp** [jonmbake/discourse-ldap-auth#15]
Hi Jon,

we've made the experience that users misunderstand the button "Login with LDAP" as a headline. They try to login with der LDAP credentials in the form fields below. After some tries they finally found out that they have to click the button.

![auswahl_172](https://cloud.githubusercontent.com/assets/1590241/20664030/ee658e12-b559-11e6-991a-1fc187635731.png)

Is it possible to improve the design of the overlay to avoid this?

Best regards
XL

**Comment by jonmbake** [comment]
The button position is set by Discourse. We could change the button color or styling to make it look more like a button.

**Comment by xldrkp** [comment]
Thanks for the quick reply. I think that could help.

**Comment by tedstrauss** [comment]
I would suggest adding a field in the plugin settings to allow customizing the string displayed by this button.

**Comment by jonmbake** [comment]
Added an icon to the button to be consistent with the other login buttons:

![Login](https://raw.githubusercontent.com/jonmbake/screenshots/master/discourse-ldap-auth/login.png)

Hopefully, this makes it look more button like, but not sure... It still might be misunderstood as a header, but I think that might be a styling problem in Discourse itself i.e. putting the login buttons above the login fields for local login w/o a header above the fields.
