### ISSUE TITLE
LDAP authentication is successful, but I get redirected to the signup page

### ISSUE THREAD

**Issue by wburningham** [jonmbake/discourse-ldap-auth#17]
I've successfully install the plugin according to the [docs](https://meta.discourse.org/t/install-a-plugin/19157) and configured it according to the [readme](https://github.com/jonmbake/screenshots/blob/master/discourse-ldap-auth/settings.png). 

I'm running v1.8.0.beta11 of discourse and 89fda80 of this plugin. Here are my settings:
![screen_shot_2017-04-28_at_3_25_10_pm](https://cloud.githubusercontent.com/assets/712078/25547968/785f95ce-2c27-11e7-91f8-b07a6cd014ac.png)

I've tried the following cases and get the following issues:

Scenario 1. With an existing user of `wesb` that is the admin and was created w/o LDAP I tried to login with LDAP. The authentication is successful according to the LDAP and rails logs, but I get redirected to the signup page where the email is omitted and the signup button is disabled.

Clicking on Login with LDAP opens another browser window and I enter in my credentials.
![screen shot 2017-04-28 at 3 19 43 pm](https://cloud.githubusercontent.com/assets/712078/25547734/278777bc-2c26-11e7-8594-e11ce3ae748a.png)

The logs say the auth is successful, but I am brought to this screen instead of logging in.
![screen shot 2017-04-28 at 3 19 52 pm](https://cloud.githubusercontent.com/assets/712078/25547735/2a3bf622-2c26-11e7-9275-a1f2f3d745bf.png)

Scenario 2. With a non-existent discourse user `jayh` I try to signup for a new account with LDAP. The authentication is successful according to the LDAP and rails logs, but I get redirected to the signup page where the email is omitted and the signup button is disabled.

When I run `tail -f /var/discource/shared/standalone/log/rails/production.log` I see the following:

```
Started GET "/auth/ldap" for 127.0.0.1 at 2017-04-28 21:30:48 +0000
(ldap) Setup endpoint detected, running now.
(ldap) Request phase initiated.
Started POST "/auth/ldap/callback" for 127.0.0.1 at 2017-04-28 21:30:57 +0000
(ldap) Setup endpoint detected, running now.
(ldap) Callback phase initiated.
Processing by Users::OmniauthCallbacksController#complete as HTML
  Parameters: {"username"=>"wesb", "password"=>"[FILTERED]", "provider"=>"ldap"}
  Rendered users/omniauth_callbacks/complete.html.erb (6.1ms)
Completed 200 OK in 12ms (Views: 2.7ms | ActiveRecord: 6.3ms)
Started GET "/u/hp.json?_=1493415042487" for 127.0.0.1 at 2017-04-28 21:30:57 +0000
Processing by UsersController#get_honeypot_value as JSON
  Parameters: {"_"=>"1493415042487"}
Completed 200 OK in 2ms (Views: 0.2ms | ActiveRecord: 0.0ms)
```

Has anyone see this issue or have any help on debugging?

**Comment by jonmbake** [comment]
Hey, @wburningham ,

Do you have _local logins_ enabled? Does your configuration match: https://github.com/jonmbake/screenshots/blob/master/discourse-ldap-auth/disable_local.png?

Jon

**Comment by wburningham** [comment]
Local logins arw not disabled. Do they need to be?

**Comment by wburningham** [comment]
I just tried disabling local logins and the same behavior/issue occurs

**Comment by jonmbake** [comment]
Any progress on this one? Scenario 1 makes sense since the user was already a "local user."; scenario 2 not so much. If you login w/ LDAP and the user account does not exist, it should automatically create the user account w/o the prompt. It seems like a configuration issue to me, but I would have to dig into the Discourse source.

**Comment by wburningham** [comment]
I figured it out. My LDAP service was authentication correctly, but was not returning the email address. Since it does user lookups via email and not by username it was failing. That also makes sense since the email was not populated in my screenshots when redirected to the signup view.

Sorry for the trouble.
