### ISSUE TITLE
Configure 'Sign Up' URL when Local Login disabled

### ISSUE THREAD

**Issue by lukebrannon** [jonmbake/discourse-ldap-auth#20]
Currently the Sign Up button redirects to the LDAP login page when Local Logins are disabled. Can we configure this behavior to point to an external URL if the LDAP service provides registration?

**Comment by jonmbake** [comment]
Hey, Luke.

There is currently not a way to configure this. The redirection is done within the Core Discourse code and I am not sure if there is a "plugin hook" to allow changing the behavior.

Jon
