### ISSUE TITLE
Plugin no longer works after Discourse upgrade

### ISSUE THREAD

**Issue by tedstrauss** [jonmbake/discourse-ldap-auth#21]
The plugin worked great, then I upgraded to  Discourse v1.9.0.beta14 +124
And now there is no more link to the LDAP login modal.

I'm getting the following errors in Discourse error logs, though I'm not sure if that's related to the problem

```
TypeError: Cannot read property 'addPreProcessor' of undefined
    at https://my.discourse.org/assets/plugin-third-party-ed07a7d5fac63719b5dadaef7c4b1315b94ebd83dabf18715bf688fbd3e5b43b.js:1:358
    at https://my.discourse.org/assets/plugin-third-party-ed07a7d5fac63719b5dadaef7c4b1315b94ebd83dabf18715bf688fbd3e5b43b.js:1:401
```

**Comment by jonmbake** [comment]
Did you try to rebuild Discourse after the upgrade?

**Comment by jonmbake** [comment]
Did you try to rebuild Discourse after the upgrade?

**Comment by tedstrauss** [comment]
The rebuild is what performed the upgrade.
It also would have upgraded the other plugins, so I'm guessing it's a bug/conflict with another plugin.

**Comment by tedstrauss** [comment]
Yup, I commented out most other plugins and rebuilt and it works again.
Will now re-add the others to figure out which one broke it.
Your plug-in is perfect.
