### ISSUE TITLE
Users unable to change e-mail address

### ISSUE THREAD

**Issue by svogt** [jonmbake/discourse-ldap-auth#30]
Hi,

not sure if this is solveable at all or just the way it is, but due to some odd circumstances some of our users have a wrong mail attribute in LDAP. If they change their e-mail address in Discourse and logout / login again, they are greeted with the new account window. So it seems the plugin now no longer finds the right account. So it seems the link between user name for login and the Discourse account is based on the e-mail address.

Any suggestions?

**Comment by jonmbake** [comment]
Hey.

If you want to look up by nickname/username, you can change line 8 of _lib/ldap_user.rb_ from `@user = User.find_by_email(@email)` to `@user = User.find_by_username(@username)`

Hope this helps.

Jon

**Comment by jonmbake** [comment]
We could also add a configuration option.
