### ISSUE TITLE
Login/registration popup is empty

### ISSUE THREAD

**Issue by MarvinKlar** [jonmbake/discourse-ldap-auth#31]
Hello everyone,

I sucessfully installed the LDAP auth plugin and registered an user with the plugin. I's kinda ugly to navigate to the url `https://forum.example.com/mySubfolder/auth/ldap` to be able to login with the account since you can't login through the default login button.

So I decided to use your tip `When disabling Local Login and other authentication services, clicking the Login or Sign Up button will directly bring up the LDAP Login popup.`

But since I configured this I got empty popups when trying to registering or loggin in:
Login:
![screenshot_1](https://user-images.githubusercontent.com/34421947/44343103-4a60c500-a48d-11e8-8a81-58449b19d2ed.png)

Register:
![screenshot_2](https://user-images.githubusercontent.com/34421947/44343106-4cc31f00-a48d-11e8-9d77-dc5ca564eb8c.png)

There are no errors in the browser's console.

Here is the latest log, but it seems fine:
https://pastebin.com/qVAe37qL

Can you tell me what I am doing wrong?

**Comment by jonmbake** [comment]
I'm not sure what is causing this; never seen this behavior before. It might give some insight if you checked out the discourse source to see the logic they use to determine if an `auth_provider` should show.

**Comment by MarvinKlar** [comment]
Do you have any idea where the relevant files are located?

**Comment by MarvinKlar** [comment]
The problem fixed itself when I updated discourse...

**Comment by ddepaoli3** [comment]
I had the same problem and solve it adding the discourse-plugin-office365-auth plugin in the discourse yml configuration. And of course rebuilding the app.
