### ISSUE TITLE
Version 0.3.6 breaks login

### ISSUE THREAD

**Issue by clarjon1** [jonmbake/discourse-ldap-auth#32]
Hello,

In our discourse install, we have been using email addresses as usernames. With the change in commit f15176f7d720d82bed7118e214b8e16a12a493a8 this causes breakage.

When a user logs in for the first time, they are given the prompt to set their email address and choose their display name.

When the user logs out, and logs back in, they are presented with this same new user dialogue, except they are informed the email address is in use already. Existing users created before this change are also unable to log in.

Reverting back to 0.3.5 allows the users to log back in.

**Comment by jonmbake** [comment]
Thanks for letting me know. I'll either revert the change or add a configuration option to specify how a user should be looked up, which defaults to email address.

**Comment by jonmbake** [comment]
@clarjon1 Can you verify v0.3.7 fixes this issue for you?
