### ISSUE TITLE
warnigs about not having an `enabled_setting` defined

### ISSUE THREAD

**Issue by andyczerwonka** [jonmbake/discourse-ldap-auth#33]
I'm getting the following warnings in the log after an upgrade to v2.1.0.beta5

![selection_008](https://user-images.githubusercontent.com/138898/44914125-80534400-acec-11e8-96b3-0ade53381523.jpg)

**Comment by jonmbake** [comment]
@andyczerwonka Thanks for the heads up. Sorry this one took so long to get to.
