### ISSUE TITLE
Error: Undefined variable: "$fa-var-sitemap".

### ISSUE THREAD

**Issue by aboettger-tuhh** [jonmbake/discourse-ldap-auth#37]
Discourse: v2.2.0.beta4 +353

When you open the page in browser you see only

```
Error: Undefined variable: "$fa-var-sitemap".
on line 5 of plugins/discourse-ldap-auth/auto_generated/plugin b5e97b66bal5dcff76b2524272bb34dd1df3b54c.css
>> content: $fa-var-sitemap;
```

**Comment by aboettger-tuhh** [comment]
**workaround:**
- fork the repo
- remove the lines in `plugin.rb`
    ```
    &:before {                                                                 
      content: $fa-var-sitemap;                                                
    }
    ```
- use the forked repo in the discourse container

**result**
no icon, but a usable login

![image](https://user-images.githubusercontent.com/17931448/49161210-ab1f5980-f328-11e8-8791-8aa15b930b27.png)

**Comment by jonmbake** [comment]
Thanks for the heads up. Looks like it was broken in https://github.com/discourse/discourse/pull/6557. Feel free to submit a PR if you have a fix!

**Comment by akhalidy-IDM** [comment]
@aboettger-tuhh fixed worked for me as well.

Thanks
