### ISSUE TITLE
TypeError with discourse 3.0.0.beta16

### ISSUE THREAD

**Issue by loganharbour** [jonmbake/discourse-ldap-auth#71]
With 0.6.0 and discourse 3.0.0.beta16, I get the following deprecation warning:

```
Deprecation warning: please give :encryption option as a Hash to Net::LDAP.new
````

And the following error:
```
(ldap) Authentication failure! ldap_error: TypeError, no implicit conversion of Hash into String
Started GET "/auth/failure?message=ldap_error&strategy=ldap" for x.x.x.x at 2023-01-06 23:02:12 +0000
Processing by Users::OmniauthCallbacksController#failure as HTML
  Parameters: {"message"=>"ldap_error", "strategy"=>"ldap"}
```

I've tried to do into this some but I'm not nearly capable enough. I tried setting `:encryption` at https://github.com/jonmbake/discourse-ldap-auth/blob/84635b1c352b2145b8e6074d94047f1e2020dcbc/plugin.rb#L37 to get rid of the deprecation warning, but still have the conversion error.

If I knew how to get a trace of the error... I'd be glad to contribute to a solution here.

First reported at https://meta.discourse.org/t/jonmbake-discourse-ldap-auth-ldap-plugin-not-working-after-upgrading-discourse-to-3-0-0-beta16/250979.

**Comment by Tris20** [comment]
Hi logan,

I wonder if updating the net-ldap gem version in the plugin.rb file helps? Looks like something similar was resolved in September last year: https://github.com/ruby-ldap/ruby-net-ldap/pull/408 

I can see version 0.17.1(from june) doesn't have this change, so you might have to specify the github path directly. 
Here are some examples of how to do that:
https://bundler.io/guides/git.html
https://stackoverflow.com/questions/2823492/install-gem-from-github-branch

Newer versions seem to also make it Ruby 3 compatible.
![image](https://user-images.githubusercontent.com/6933318/211127889-a0d6dbf5-9222-4d34-89e3-85dc95a5383b.png)

**Comment by bdecotte** [comment]
Good call ! It works 👍 
(do not bump omniauth-ldap to 2.0.0 though :
Unable to activate omniauth-ldap-2.0.0, because omniauth-1.9.2 conflicts with omniauth (~> 1.8.1), rubyntlm-0.3.4 conflicts with rubyntlm (~> 0.6.2) )

**Comment by jonmbake** [comment]
Glad you found a fix 🎉 Can you submit a pull request with the fix?

**Comment by loganharbour** [comment]
Closed by https://github.com/jonmbake/discourse-ldap-auth/pull/72

Thanks all!
