### ISSUE TITLE
problem when using /forum to access discourse

### ISSUE THREAD

**Issue by lud0vicb** [jonmbake/discourse-ldap-auth#8]
hello

my discourse is running behing a nginx proxy. I can access discourse through url like : https://XXX.YYY.ZZ/forum
I had to install nginx on host and to redirect http(s) cnx to 2 sockets in /shared directory. The container's nginx has to listen to those sockets to receive packets.
I had to change the long polling parameter in discourse admin page.

I have a problem with this plugin. When I click on login button, discourse shows me a banner. I have to click on "login whith ldap".
Discourse shows me an other banner : https://xxx.yyy.zz/forum/auth/ldap 
I wrote ldap login and password and click on sign in button.
Here is the problem. This redirects me to https://xxx.yyy.zz/auth/ldap/callback. The /forum subdirectory in the url is lost during the redirect. So it does not work.

note : I used this plugin without the /forum hack ; it works perfectly 
note2 : I'am able to make it works by adding a this line to nginx conf 
  rewrite ^/auth/ldap/(.*)$ /forum/auth/ldap/$1 last;

**Comment by jonmbake** [comment]
Hey, @lud0vicb. This appears to be an issue with the dependency, `omniauth-ldap` ie it doesn't provide a way to easily set the `callback_path`. There is relavent discussion here: https://github.com/intridea/omniauth-ldap/pull/16#issuecomment-83026356. You might be able to monky patch and hard code in your `callback_path` like in this comment: https://github.com/intridea/omniauth-ldap/pull/16#issuecomment-83026356:
